### ISSUE TITLE
property 'centerToPath' of undefined

### ISSUE THREAD

**Issue by stuartmemo** [jeremyckahn/stylie#22]
JS error stops Stylie working at all. Renders blank page. Happens on http://jeremyckahn.github.io/stylie/ and locally.

**Comment by jeremyckahn** [comment]
Oh no!  So sorry about that.  [Silly mistake on my part](https://github.com/jeremyckahn/stylie/commit/749f129b102e0b657b0755edf26c484fc7afb3ac), and I missed it because the issue only affects users who haven't used Stylie previously and therefore have no data in `localStorage`.  Please visit http://jeremyckahn.github.io/stylie/ again, refresh the page twice quickly (this will bust the application cache and pull down the latest code) and run this in your browser's JS console:

````javascript
localStorage.clear();
````

...And refresh again.  Please let me know if this gets the app working for you.  Thanks for reporting!

**Comment by stuartmemo** [comment]
Amazing, works a treat. Thanks very much!

**Comment by stuartmemo** [comment]
Oh, FYI the double refresh didn't work. Had to open devtools and delete it from localStorage manually.

**Comment by jeremyckahn** [comment]
You're welcome!  The double refresh usually busts application cache for me.  If that doesn't work, you may need to remove the cached code from chrome://appcache-internals/.  Not ideal, I realize, but hopefully issues like this won't come up very often (or ever again).

To clarify, a quick double-refresh will not affect `localStorage`, only application cache.
